---
title: "Daily Schedule"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<button class="accordion">Before Starting the Program</button>
<div class="panel"> 

| To-Do         |                              | 
|---------------|------------------------------------|
| Download and Install R | [Link](https://mirror.las.iastate.edu/CRAN/) [Video](https://uci.yuja.com/V/Video?v=3173351&node=10757512&a=280036139&autoplay=1)|
| Download and Install RStudio| [Link](https://www.rstudio.com/products/rstudio/download/)  [Video](https://uci.yuja.com/V/Video?v=3173359&node=10757552&a=664679852&autoplay=1)|
|Setup RStudio| [Video](https://uci.yuja.com/V/Video?v=3173384&node=10757676&a=717681262&autoplay=1)       |
|Download packages |<a href="R-code/code-00-setup.R" download>File</a> [Video](https://uci.yuja.com/V/Video?v=3173415&node=10757778&a=1269482034&autoplay=1)|
|Alzheimer's Disease | [Link](https://www.youtube.com/watch?v=LrcL3vJjN2g) |

</div>


	
	
```{r}
htmltools::tagList(
  htmltools::tags$script(src = "https://d3js.org/d3.v4.min.js"),
  htmltools::tags$script(src = "https://cdnjs.cloudflare.com/ajax/libs/dimple/2.3.0/dimple.latest.min.js")
)
```

```{js, class.source = "jsvis1"}
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    /* Toggle between adding and removing the "active" class,
    to highlight the button that controls the panel */
    this.classList.toggle("active");

    /* Toggle between hiding and showing the active panel */
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
```
